name: UHCMeetup
version: 1.0
main: me.puugz.meetup.UHCMeetup
author: puugz
website: https://github.com/puugz

commands:
  forcestart:
    aliases: [fs]
    permission: uhcmeetup.command.forcestart
  setspawn:
    permission: uhcmeetup.command.setspawn
  stats:
    aliases: [statistics]
